[package]
name = "pomodoro_daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
pomodoro_core = { path = "../core" }
ctrlc = "3.1.9"
rusqlite = "0.25.3"
notify-rust = "4"
serde = "1.0.133"
serde_derive = "1.0.133"
serde_json = "1.0"
ws = "0.9.2"
